// src/core/types/hono.types.ts
import type { Context } from "hono";
import type { DependencyContainer } from "tsyringe";

// Use the global `Env` interface generated by Wrangler in worker-configuration.d.ts
export type AppEnv = {
  Bindings: Env;
  Variables: {
    container: DependencyContainer;
  };
};

export type HonoContext = Context<AppEnv>;
