// src/core/types/hono.types.ts
import type { DependencyContainer } from "tsyringe";

// Use the global `Env` interface generated by Wrangler in worker-configuration.d.ts
export type HonoContext = {
  Bindings: Env;
  Variables: {
    container: DependencyContainer;
  };
};
